// Root layout for the entire application
// Wraps all pages
// Includes global providers (AuthProvider)
// No authentication logic here

import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
